# Generated by Django 4.1.3 on 2022-12-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart_cartiteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupan',
        ),
    ]
