# Generated by Django 4.1.3 on 2022-12-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_coupan'),
        ('account', '0006_alter_cartiteams_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.coupan'),
        ),
    ]
